name: Test For Secrets to Files

jobs:
  save_and_upload_env:
    runs-on: ubuntu-latest
    if: contains('/ref/head/main', github.ref)

    steps:
    - name: 'Clone Repository'
      uses: actions/checkout@v2
    
    - name: 'Save Secrets to File'
      run: |
        echo "${{ secerts.ENV_MASTER }}"
        echo "${{ secerts.ENV_MASTER }}" > sample.env
    
    - name: 'Upload File to Share'
      run: |
        curl -k -u ${{ secerets.SHARE_USER }}:${{ secerets.SHARE_PASS }} -T ./sample.env \
        https://share.vphrase.com/remote.php/dav/files/tiyaskar/
    
    

