name: Test For Secrets to Files

on:
  workflow_dispatch:

jobs:
  save_and_upload_env:
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref)

    steps:
    - name: 'Clone Repository'
      uses: actions/checkout@v2
    
    # - name: 'Save Secrets to File'
    #   run: |
    #     echo "${{ secrets.ENV_MASTER }}"
    #     echo "${{ secrets.ENV_MASTER }}" > sample.env.txt
    
    # - name: 'Upload File to Share'
    #   run: |
    #     curl -k -u ${{ secrets.SHARE_USER }}:${{ secrets.SHARE_PASS }} -T ./sample.env.txt \
    #     https://share.vphrase.com/remote.php/dav/files/tiyaskar/
    - name: Cache libxml2-utils
      uses: actions/cache@v2
      id: cache-libxml2-utils
      with:
          path: "libxml2-utils"
          key: libxml2-utils
    - name: Install libxml2-utils
      if: steps.cache-libxml2-utils.outputs.cache-hit != 'true'
      run: |
          apt -y install libxml2-utils
    - name: Get xmllint version info
      run: |
          xmllint --version
    
    

